fix(general-match.md): 更正 note/tip 范围的错误 (#4709)
* feat(general-match.md): 添加“基于高斯消元的一般图匹配算法”部分

* style: format markdown files with remark-lint

* Apply suggestions from code review

把原来 435 行被 bot 改成行内的公式改回行外

Co-authored-by: Tifa <62847935+Tiphereth-A@users.noreply.github.com>

* style: format markdown files with remark-lint

* fix LaTeX format errors caused by bot

* added "参考资料"

* style: format markdown files with remark-lint

* fix & refactor: fix indent & Put example into file

* style: format markdown files with remark-lint

* Apply suggestions from code review (2.2)

Co-authored-by: yusancky <yusancky@hotmail.com>

* fix "undefined reference to \"main\""

* Revert "fix "undefined reference to \"main\"""

This reverts commit 9788a25ac32d6ee64ad3dab1ec879899498160d0.

* fix sample code (for blossom) and blossom

* fix general-match_1.ans

* changed random seed to 114514 & fix answers

* small fix

* fix 2.in & 2.ans

* Update docs/graph/graph-matching/general-match.md

Co-authored-by: yusancky <yusancky@hotmail.com>

* fix issues with note/tip

* 2.8

---------

Co-authored-by: 24OI-bot <15963390+24OI-bot@users.noreply.github.com>
Co-authored-by: Tifa <62847935+Tiphereth-A@users.noreply.github.com>
Co-authored-by: yusancky <yusancky@hotmail.com>